import "@/styles/globals.css";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Provider } from "react-redux";
export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Mihaqi | Chinese curtain fabric supplier</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
               
            </Head>
            <div>
                <Header />
                <Component {...pageProps} />
                <Footer />
            </div>
        </>
    );
}